print("Welcome to the Interactive Personal Data Collector")
name=input("Please enter your name:")
age=int(input("Please enter your age:"))
ht=input("Please enter your height in ft:")
fav_num=input("Please enter your favourite number:")
print("Thankyou, Here is the information we collected:", end="\n\n")
print("Name:", name, "(Type:", type(name), id(name))
print("Age:", age, "(Type:", type(age), id(age))
print("Height:", ht, "(Type:", type(ht), id(ht))
print("Favourite Number:", fav_num, "(Type:", type(fav_num), id(fav_num))
print("Your birth year is approximately:", 2026 - age, "(based on your age of", age)
print("Thankyou for using the Personal Data Collector. Have a Good Day!")
